---
- name: Disable Default Redis
  shell: dnf module disable redis -y

- name: Enable Redis 7
  shell: dnf module enable redis:7 -y

- name: Install Redis
  dnf:
    name: redis
    state: present

- name: Allow Remote Connections
  replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Disable Protected Mode
  replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Start and Enable Redis
  service:
    name: redis
    state: started
    enabled: yes