---
- name: Install Maven
  dnf:
    name: maven
    state: present

- name: Setup Common
  include_role:
    name: common

- name: Download Shipping Code
  get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
    dest: /tmp/shipping.zip

- name: Unzip Shipping Code
  unarchive:
    src: /tmp/shipping.zip
    dest: /app
    remote_src: yes

- name: Build Application
  shell: cd /app && mvn clean package

- name: Move Jar File
  shell: mv /app/target/shipping-1.0.jar /app/shipping.jar

- name: Copy Shipping Service
  template:
    src: shipping.service.j2
    dest: /etc/systemd/system/shipping.service

- name: Reload Daemon
  systemd:
    daemon_reload: yes

- name: Start and Enable Shipping
  service:
    name: shipping
    state: started
    enabled: yes

- name: Install MySQL Client
  dnf:
    name: mysql
    state: present

- name: Check If Schema Loaded
  shell: mysql -h {{ MYSQL_HOST }} -uroot -pRoboShop@1 -e "use shipping"
  register: schema_check
  ignore_errors: yes

- name: Load Schema
  shell: mysql -h {{ MYSQL_HOST }} -uroot -pRoboShop@1 < /app/db/schema.sql
  when: schema_check.rc != 0

- name: Load App User
  shell: mysql -h {{ MYSQL_HOST }} -uroot -pRoboShop@1 < /app/db/app-user.sql
  when: schema_check.rc != 0

- name: Load Master Data
  shell: mysql -h {{ MYSQL_HOST }} -uroot -pRoboShop@1 < /app/db/master-data.sql
  when: schema_check.rc != 0

- name: Restart Shipping
  service:
    name: shipping
    state: restarted