[web]
172.31.25.212
[web:vars] 
course=invcourse 


[frontend]
172.33.55.11 
156.78.22.30
66.77.88.99


[mongodb]
mongodb-dev.daws88sdev.online

[catalogue]
catalogue-dev.daws88sdev.online

[redis]
redis-dev.daws88sdev.online

[user]
user-dev.daws88sdev.online

[cart]
cart-dev.daws88sdev.online

[mysql]
mysql-dev.daws88sdev.online

[shipping]
shipping-dev.daws88sdev.online

[rabbitmq]
rabbitmq-dev.daws88sdev.online

[payment]
payment-dev.daws88sdev.online

[frontend]
frontend-dev.daws88sdev.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.daws88sdev.online
CATALOGUE_HOST=catalogue-dev.daws88sdev.online
REDIS_HOST=redis-dev.daws88sdev.online
USER_HOST=user-dev.daws88sdev.online
CART_HOST=cart-dev.daws88sdev.online
MYSQL_HOST=mysql-dev.daws88sdev.online
SHIPPING_HOST=shipping-dev.daws88sdev.online
RABBITMQ_HOST=rabbitmq-dev.daws88sdev.online
PAYMENT_HOST=payment-dev.daws88sdev.online