---
- name: Create Roboshop User
  user:
    name: roboshop
    system: yes
    home: /app
    shell: /sbin/nologin
    comment: "roboshop system user"
  ignore_errors: yes

- name: Create App Directory
  file:
    path: /app
    state: directory

- name: Remove Old Code
  file:
    path: /app
    state: absent

- name: Recreate App Directory
  file:
    path: /app
    state: directory